### ISSUE TITLE
resnet example? pre-trained example?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [ajtulloch/caffegraph#18]
I'd like to see a resnet example, as an notebook, if possible.

A notebook that re-uses pre-trained weights would be very useful - a way to actually get results without having to re-train.

**Comment by ajtulloch** [comment]
TBH this isn't really a project I'd recommend using - some of the ideas are a part of @dmlc/nnvm (@tqchen), but it's not really a thing I'd recommend using for anything serious. TensorFlow, MXNet, etc are probably better tools.
